### ISSUE TITLE
VanDam to ChildRecords tutorial

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#105]
https://github.com/LAAC-LSCP/ChildRecordsData/blob/docs-improvements/docs/TUTORIAL_VANDAM.md

**Comment by alecristia** [comment]
I was looking over the daylong vandam and realized that, actually, there are three types of annotation: .its, .rttm (generated by vtc over the course of corpus adaptation), and *human*, inside .cha file. 

.cha is a very standard file in language acquisition, I think there could be packages we can rely on:

- https://github.com/SeedlingsBabylab/pyclan
- https://github.com/SeedlingsBabylab/parse_clan2
- https://jacksonllee.com/papers/lee-etal-2016-pylangacq.pdf

This will probably increase interest, and would make this dataset also a good example for ChildRecordsR @alsonicr !
