### ISSUE TITLE
zooniverse pipeline improvements

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#110]
--excluded-segments export1.csv export2.csv
 --skip-segments export1.csv export2.csv : matching segments should not be resubmitted
  - allow upload w/o chunkify

**Comment by lucasgautheron** [comment]
```
child-project sampler {random|high-volubility|etc.}
```

Output : segments.csv

```
child-project annotation-templates etc.
```

```
child-project zooniverse {extract-chunks|upload-chunks|retrieve-classifications}
```

**Comment by lucasgautheron** [comment]
Since we have decoupled the samplers from zooniverse, I think this is no longer needed. Do you agree, @alecristia ?
If you do, then I'll close this issue.

**Comment by alecristia** [comment]
sorry, why isn't it needed? i thought this issue allows users to avoid sections that have already been sampled... so it's still relevant, no?

**Comment by lucasgautheron** [comment]
Well, maybe -- but the user could remove the segments that should be avoided by himself before passing the dataframes to, for instance, `child-project zooniverse extract-chunks`

if we don't want to leave that to the user, than, maybe I could think of a more efficient way to do it on our end!
