### ISSUE TITLE
cheat sheet in the docs

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/ChildRecordsData#115]
it would be great to have a cheat sheet somewhere in the docs, with a list of commands you need to do once in a while:

- getting annotations or some other part that is not typically downloaded
- updating the package
- pulling updates from datasets
- saving updates
- publishing updates

**Comment by lucasgautheron** [comment]
Don't you think this would be redundant with https://github.com/LAAC-LSCP/ChildRecordsData/blob/docs-improvements/docs/REUSE.md in a way ?

Maybe we should think about what we should do to make this look more like a cheatsheet.

Apart from the cheatsheet, we'd have two tutorials: 
 - The VanDam tutorial, to package a dataset to our format
 - The Namibia tutorial, to install namibia-data, get the data, submit updates etc.

What do you think?
