### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by camiscaff** [LAAC-LSCP/ChildRecordsData#117]
Hi!
so I have a first error:
install_github("LAAC-LSCP/ChildRecordsData")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`LAAC-LSCP`) and repo name (`ChildRecordsData`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by lucasgautheron** [comment]
Hi,

Well, sorry, this is a python package, not R :) You need to install it with pip ! See more instructions here: https://github.com/LAAC-LSCP/ChildRecordsData#installation

**Comment by camiscaff** [comment]
Im trying to install nicolas package on R following the instructions provided here so far https://laac-lscp.github.io/ChildRecordsR/

**Comment by lucasgautheron** [comment]
Ah I see!
Two things:
 - You did `install_github("LAAC-LSCP/ChildRecordsData")`, but you should do `install_github("LAAC-LSCP/ChildRecordsR") then
 - You might want to create an issue here instead: https://github.com/LAAC-LSCP/ChildRecordsR/issues
