### ISSUE TITLE
datalad update error

### ISSUE THREAD

**Issue by camiscaff** [LAAC-LSCP/ChildRecordsData#118]
(

hi! 
I followed the instruction so far but I got this error at the datalad update level 

ChildProjectVenv) (base) 18:13:00 lscpuser@camila: tsimane2017-data $ datalad update
[INFO   ] Fetching updates for <Dataset path=/Users/lscpuser/tsimane2017-data> 
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
cscaff@cognitive-ml.fr's password: 
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
[ERROR  ] Cmd('git') failed due to: exit code(128)
|   cmdline: git fetch --progress --prune --recurse-submodules=no -v scratch1
|   stderr: 'fatal: '/scratch1/data/laac_data/tsimane2017-data' does not appear to be a git repository
| CommandError: command '['ssh', '-o', 'ControlPath="/Users/lscpuser/Library/Caches/datalad/sockets/e9668fda"', 'oberon', 'export "PATH=/usr/lib/git-annex.linux:$PATH"; git-upload-pack \'/scratch1/data/laac_data/tsimane2017-data\'']' failed with exitcode 128
| Failed to run ['ssh', '-o', 'ControlPath="/Users/lscpuser/Library/Caches/datalad/sockets/e9668fda"', 'oberon', 'export "PATH=/usr/lib/git-annex.linux:$PATH"; git-upload-pack \'/scratch1/data/laac_data/tsimane2017-data\''] under None. Exit code=128.
| fatal: Could not read from remote repository.
| 
| Please make sure you have the correct access rights
| and the repository exists.' [cmd.py:wait:412] (GitCommandError)

**Comment by lucasgautheron** [comment]
Hey,

Well, unfortunately Oberon is down, so you can't get the data until it is back online :(

**Comment by camiscaff** [comment]
that explains so MUCH!

**Comment by lucasgautheron** [comment]
well, oberon seems backup, but scratch1 is empty atm - so we'd better wait the maintenance to be over anyway!
