### ISSUE TITLE
Heterogenous recordings

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#120]
**Is your feature request related to a problem? Please describe.**

Listening to Kaya de Barbaro's talk, I am thinking we should support heterogenous recordings (such as sensor data) along with the audio.

**Describe the solution you'd like**

Add the following columns to recordings.csv:

- `session_id`
- `session_offset`: offset to align a given recording with others from the same session (identified by `session_id`). i.e, once all recordings have been shifted by `session_offset` seconds, they are aligned.
- For now `recording_device_type` can help distinguish the recorders and even other kinds of sensors.

**Comment by alecristia** [comment]
RE problem: this is definitely something on behive/echolalia's mind!!

(it would be SO cool to have heart rate data together with audio data)

**Comment by lucasgautheron** [comment]
I think it does not require much work on our end.
We could have several sets of recordings (just as we do for annotations), for instance: `audio`, `heart-rate`, `accelerometer` etc.
They'd all lie in recordings/ and be indexed in the metadata as well. 
But then they should be sync'd, so start_times at the second level (or even better) should be achieved...

**Comment by lucasgautheron** [comment]
Actually, @alecristia, we already need this for Marvin's pilot, because we will need aligned LENA/BabyLogger recordings.

Here is my suggestion:

Add the following columns to recordings.csv:

- `session_id`
- `session_offset`: offset to align a given recording with others from the same session (identified by `session_id`). i.e, once all recordings have been shifted by `session_offset` seconds, they are aligned.
- For now `recording_device_type` can help distinguish the recorders and even other kinds of sensors.

What do you think ?
In reality, the shift might not be constant, /but/ I think this is enough for now...

**Comment by lucasgautheron** [comment]
The only thing I don't like so much with the `session_id` is that it is one more ad-hoc information, when maybe we could find a more natural way to mimic it.

**Comment by alecristia** [comment]
agreed on the fact that shift isn't constant but this is good enough for now.
For an improved version, I wonder if the routines you developed for Solomon could be used to tag recs as being suspect if the shift is very large?

RE `session_id` you mean something like date & time of start (rounded to something reasonable for all recs)?

**Comment by lucasgautheron** [comment]
> agreed on the fact that shift isn't constant but this is good enough for now.
> For an improved version, I wonder if the routines you developed for Solomon could be used to tag recs as being suspect if the shift is very large?
We could use that, or try something more sophisticated. @MarvinLvn mentioned https://en.wikipedia.org/wiki/Dynamic_time_warping. If the mapping function can be roughly approximated by a simple, constant translation everything is fine, but we could tag the recordings for which the approximation does not hold. I might give a try to this technique. We could have some function in our package to compute the shift between pairs of recordings !

> RE `session_id` you mean something like date & time of start (rounded to something reasonable for all recs)?
It could be that or something like. e.g. "20200102_child1", i don't know. So that's what bothers me, it is a bit ad-hoc - although it is necessary to group all simultaneous recordings by "something". And we might want to leave the possibility of several sessions occurring the same day. So I don't think we can escape this ad-hoc `session_id` for now...
