### ISSUE TITLE
annotations path convention

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#141]
There are two possibilities for the annotation index:

 - make both raw_filename and annotation_filename paths relative `annotations/<set>/raw` and `annotations/<set>/converted`
 - make them relative to annotations/

The first option makes the life of the users a bit easier, but it makes the life of the maintainers harder (in case annotations are moved around, etc.)

Which one to choose ?

**Comment by lucasgautheron** [comment]
There is one more argument against doing that, which you might want to consider.

The `raw_filename` is injected into converted annotations, so that we can trace which input annotation(s) each segment root from. If the paths are relative to annotations/, and the annotation set is renamed, then the raw files will be moved, and all the annotations will need to be updated accordingly...

**Comment by lucasgautheron** [comment]
Anyway here is a PR that does what you want, but the more I think about it, the less I think we should be doing it this way...

https://github.com/LAAC-LSCP/ChildRecordsData/pull/160/files

**Comment by alecristia** [comment]
yikes, that sounds like opening a can of worms, if all annotations need to be re-edited!

**Comment by lucasgautheron** [comment]
Well anyway I have implemented both options so we just have to decide !

#160 vs #163
