### ISSUE TITLE
Questions for Alex

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#36]
- Any opinion on https://github.com/LAAC-LSCP/ChildRecordsData/issues/70 ?
- Any opinion on https://github.com/LAAC-LSCP/ChildRecordsData/issues/68 ?
- ~~Can you please confirm that tsimane2017 is properly formatted (i.e. no recordings or meta data missing) in /scratch1/data/laac_data/ ?~~
- ~~I have two sets of recordings for vanuatu, those at /scratch1/projects/ac_lacie01/STRUCTURE/raw/vanuatu and those uploaded by Heidi. I only have metadata for the 20 first. Where can I get all meta-data for this project ?~~
-  ~~What would be the csv conversion for this RTTM file ? https://github.com/LAAC-LSCP/ChildRecordsData/pull/21#issuecomment-712210550~~
- ~~Can we get credits for Jean Zay to run the VTC on Solomon ?~~
-  ~~Can you please send me the credentials to retrieve Vandam data on mattermost ?~~
- ~~regarding png VTC: https://github.com/LAAC-LSCP/ChildRecordsData/issues/45#issuecomment-717777465~~
- ~~in the TODO list, task ID 7 (Solomon) : "using the annotations in laac-solis, estimate inter-rater reliability and voice type classifier performance". Where can i find these ?~~
- ~~It would be great if you could review all my comments in the annotation management PR : https://github.com/lucasgautheron/ChildRecordsData/pull/21, happy to discuss this together if necessary~~

**Comment by alecristia** [comment]
I owe you a reply on the tsimane data and Jean Zay, but I think the rest are handled elsewhere. Tell me if not!
