### ISSUE TITLE
stats wishlist

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#41]
- get time-stamped stats at 5 mins & 60 mins blocks* (removing incomplete blocks -- eg in a 33 min rec, I'd have 6 5-min blocks and 0 60-min blocks)
- get stats over the whole file*
- get stats per hour (mean, min, max, med - across all hours; OR within user-provided range: eg 11-13 for mealtime, 7-19 for daytime)

For the following event types, get total duration, average duration, median duration, number:
KCHI/CHI: child vocalizations (VTC: KCHI & LENA: CHN), †child veg vocs (LENA: vfx), †child veg vocs (LENA: utt), child cry vocs (VCM: Y & LENA: cry), †child can vocs (VCM: C), †child non-can vocs (VCM: N)
OCH/CXN, FEM/FAN, MAL/MAN

For conversational stats, looks like chattr has it all:

- Rate of turn-taking (i.e., rate of child--other and other--child transitions)
- Frequency and duration of interactional sequences
- Speed of turn transitions
- Hourly and daily trends in interactional bursts
- Ratio of vocalization by the child and others during turn exchanges
- Differences in turn-taking between the child and different family members

**Comment by alecristia** [comment]
I'm reassigning this to Nicolas, who is already working on it!

**Comment by alsonicr** [comment]
I will look at chattr function on the data then

**Comment by lucasgautheron** [comment]
We all do agree that these scripts should take this format as an input right : https://laac-lscp.github.io/ChildRecordsData/FORMATTING.html#annotations-format ?

It would be nice if they were integrated in the package maybe. @alsonicr, are you writing them in R or python ?

**Comment by alsonicr** [comment]
I'm fine with every input you previously decided. Currently I use rttm or the standardized format you produce.  

I'm currently writing function in R, nothing to fancy. 

@alecristia told me Chattr is not in a finish yet and i would agree looking at the github (look messy). More over, Chatter take rttm file as input or its if we look at the description. But from what i understand we are moving from those formats to a common one off our own.
