### ISSUE TITLE
PNG VTC

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/ChildRecordsData#45]
37 files found through this pattern:
`/scratch1/data/raw_data/png2019/lena_exports_09_17_2019/*/e*wav`

(there are a few more small files in there which can be ignored, like c19/Têpa, c19_20190821_1725.wav -- that's just a section of the long file)

Please note I don't have edit rights in that folder, so look out for potential access errors

**Comment by lucasgautheron** [comment]
Can this wait the migration of PNG data ? Once recordings are migrated, it takes two scripts to perform the whole process (once for conversion, once for launching VTCs on Oberon)

**Comment by lucasgautheron** [comment]
https://github.com/LAAC-LSCP/png2019-data/tree/master/annotations/vtc
