### ISSUE TITLE
transform human annotations from raw textgrid format to LG's new scheme

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/ChildRecordsData#53]
I think the instructions are:
Import annotations
`python import_annotations.py --source /path/to/project --annotations /path/to/dataframe.csv`

In context:
https://laac-lscp.github.io/ChildRecordsData/#validate-raw-data

See also for sample script:
https://github.com/LAAC-LSCP/ChildRecordsData/issues/15

Location of primary annotator's annotations:

`/scratch1/projects/ac_lacie01/STRUCTURE/namibie/data/*/derived/*/*_m1.TextGrid`

Please note: **we only care about _m1.TextGrid; ignore the other TextGrids in those folders!!!!**

Location of secondary annotators' annotations:
`Dropbox/_nam_stab_chi/recoding_project/tg/*mm.TextGrid`
`Dropbox/_nam_stab_chi/recoding_project/tg/*ak.TextGrid`

For all annotations, the naming convention is project_child_recordingDate_recordingNumber_onsetOfClip_annotatorCode -- example: namibie_aiku_20160714_1_12600_m1

By "onsetOfClip" we mean that zero seconds in this TextGrid corresponds to onsetOfClip seconds from the beginning of the audio.

**Comment by lucasgautheron** [comment]
Here is one more example that might help : https://github.com/LAAC-LSCP/ChildRecordsData/blob/master/examples/import_vtc.py vtc rttm's

**Comment by lucasgautheron** [comment]
Hello @alsonicr, I've made a change to make your life easier. You can now import one annotation at a time using the importation, without having to deal with dataframes at all. See the docs :) https://laac-lscp.github.io/ChildRecordsData/#single-importation

**Comment by alsonicr** [comment]
I may get it wrong but you want me to do it on the server, if i guess well ?

**Comment by lucasgautheron** [comment]
You can copy the data to /scratch2/, import everything, and them move your files to /scratch1/ when you're done
it is much better not to work directly on /scratch1/ :)
