### ISSUE TITLE
Data quality flags

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#68]
List of proposed quality flags to add to projects metadata :

<table>
<tr>
<th>Table</th>
<th>Name</th>
<th>Description</th>
<th>Required?</th>
</tr>
<tr>
<td>recordings</td>
<td>might_feature_gaps</td>
<td>1 if the audio cannot be guaranteed to be a continuous bloc, 0 or undefined otherwise.</td>
<td>optional</td>
</tr>
<tr>
<td>recordings</td>
<td>noisy_setting</td>
<td>1 if the audio may be noisier than the child's usual day, 0 or undefined otherwise</td>
<td>optional</td>
</tr>
<tr>
<td>recordings</td>
<td>start_time_accuracy</td>
<td>(minute|hour|unreliable)</td>
<td>optional, otherwise assume minute</td>
</tr>
</table>

Feel free to suggest more !

**Comment by alecristia** [comment]
to recordings, noisy_setting

Examples (all real life):

- that day happened to have a wedding next door
- a truck had an accident in the road
- we were the first white people the villagers had seen in years -- so everyone stayed where we were, chatting...
