### ISSUE TITLE
png

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#7]
**Author**: Alex
**Ask**: Alex
**Record device**: LENA (a little babylogger)
**Raw data**: /scratch1/data/raw_data/png2019/
**Structured data**:

**Comment by alecristia** [comment]
- [ ] correct errors of missing files, sex, ages
- [ ] generate missing wav file
- [ ] write annotations import script based on #22 
- [ ] vtc the files that haven't yet been done
- [ ] get the rttms and wavs etc well organized
