### ISSUE TITLE
Providing exact audios durations in the metadata ?

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#70]
What do you think ?

**Comment by alecristia** [comment]
Is this a check for the human, or are they provided automatically when the data are checked during import?

If the latter, I'm all for it!!!

**Comment by lucasgautheron** [comment]
They should be reliable, so computed automatically.
Sometimes you need the duration, but don't want to download the audio, so it would be useful in this case !
