### ISSUE TITLE
Doc improvements

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildRecordsData#84]
- Documentation : la penser de manière fonctionnelle
 - Deux pages : comment créer un dataset et comment recuperer un dataset
 - Idee alternative : tutoriels depuis un sommaire
 - Separer la description technique et les tutoriels
 - Split la doc en pages et restreindre le sommaire aux idees generales
 - Introduire des schemas tires des slides pour LIFT

**Comment by alecristia** [comment]
- [ ] Documentation : la penser de manière fonctionnelle **in progress**
 - [x] Deux pages : comment créer un dataset et comment recuperer un dataset
 - [x] Split la doc en pages et restreindre le sommaire aux idees generales
 - [x] Introduire des schemas tires des slides pour LIFT

Also did

 - [ ] Added background info in zooniverse, but indeed more hand-holding is needed there

Later

 - [ ] Separer la description technique et les tutoriels
 - [ ] Idee alternative : tutoriels depuis un sommaire -- not sure I remember what we intended?

In general, I'm still not sure myself of being able to set up a dataset from scratch...

**Comment by lucasgautheron** [comment]
- explicit how to check which version of python pip refers to
