### ISSUE TITLE
importing .its into our standardized annotation format for import

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/ChildRecordsData#87]
There are two versions of .its. Here is one of them, from https://homebank.talkbank.org/access/Public/VanDam-Daylong.html: [e20100728_143446_003489.its.zip](https://github.com/LAAC-LSCP/ChildRecordsData/files/5796028/e20100728_143446_003489.its.zip)

I owe an example of the newer one. @lucasgautheron can you let me know when you're done with the above, so I find one?

**Comment by lucasgautheron** [comment]
Regarding LENA speakers, since we would like to fit them into our categories (MAL, FEM, CHI, OCH), what do you think of the following translation table ?

```python
lena_speaker_translation_table = {
    'CHN': 'CHI',
    'CXN': 'OCH',
    'FAN': 'FEM',
    'MAN': 'MAL',
    'OLN': 'OLN',
    'TVN': 'TVN',
    'NON': 'NON',
    'SIL': 'SIL',
    'FUZ': 'FUZ',
    'TVF': 'TVF',
    'CXF': 'OCH',
    'NOF': 'NON',
    'OLF': 'OLN',
    'CHF': 'CHI',
    'MAF': 'MAL',
    'FAF': 'FEM'
}
```

**Comment by lucasgautheron** [comment]
We should also discuss what information we'd like to retrieve and which columns to add, e.g. maybe a column lena_conversation_no

**Comment by alecristia** [comment]
> ```python
> lena_speaker_translation_table = {
>     'CHN': 'CHI',
>     'CXN': 'OCH',
>     'FAN': 'FEM',
>     'MAN': 'MAL',
>     'OLN': 'OLN',
>     'TVN': 'TVN',
>     'NON': 'NON',
>     'SIL': 'SIL',
>     'FUZ': 'FUZ',
>     'TVF': 'TVF',
>     'CXF': 'CXF',
>     'NOF': 'NON',
>     'OLF': 'OLN',
>     'CHF': 'CHF',
>     'MAF': 'MAF',
>     'FAF': 'FEF'
> }
> ```

or you can map the F-final to silence, because they predominantly are that

RE info to pull out, I'd vote for adding columns for all of the things that it's counting, chi vocs, ct's, even db's -- it'll be a wide table but this way no info gets lost. thoughts?

**Comment by lucasgautheron** [comment]
Alright !

So let's take this piece of its as an example:

```xml
<Segment
  spkr="FAN"
  average_dB="-36.34"
  peak_dB="-28.41"
  conversationInfo="|EC|23|4|0|AMF|NT|FI|"
  femaleAdultWordCnt="2.61"
  femaleAdultNonSpeechLen="P0.00S"
  femaleAdultUttCnt="0"
  femaleAdultUttLen="P0.00S"
  startTime="PT545.14S"
  endTime="PT545.74S" 
/>
```

These are the columns I am thinking of adding:

 - lena_conversation_number
 - lena_conversation_type (either `conversation` or `pause`)
 - words
 - non_speech_length
 - average_db
 - peak_db
 - utterances_count
 - utterances_length
 
I am wondering when is the lena_ prefix useful/needed for these new columns. I would say when something has very little chance of having an equivalent in any other system


How shall we understand this ? `conversationInfo="|EC|23|4|0|AMF|NT|FI|"`

Just thinking out loud...

**Comment by lucasgautheron** [comment]
https://cdn.shopify.com/s/files/1/0596/9601/files/LENA_Pro_User_Guide.pdf
https://www.lena.org/technology/#tech-reports
https://www.lena.org/wp-content/uploads/2016/07/LTR-04-2_ITS_File.pdf
https://www.lena.org/wp-content/uploads/pdf/technical-reports/LTR-11-1_Vocal%20Productivity.pdf

**Comment by alecristia** [comment]
> conversationInfo="|EC|23|4|0|AMF|NT|FI|"

these also should be pulled apart, because they have meanings. You may have learned them by now - if not, let me know! For instance, the numbers are running counts of things like child ling vocs -- and the only way to have them is like this, because there's no precise way to estimate them from other info. (I can explain this).

RE the LENA prefix, I don't think it's needed because the "type" of the annotation will establish that this is LENA, and for some it is conceivable to obtain equivalent info. For instance, average and peak db, via a different method. So I'd vote no prefix.

RE "lena_conversation_type" -- there are conversation types in LENA (which may be in the level above segments), so we should call this "blocks".

See also this code, which may explain some of the info and give you ideas about how to pull out things: 

https://github.com/HomeBankCode/rlena

**Comment by alecristia** [comment]
new version .its

[LENAExport_ITSFiles_202012350_091222.zip](https://github.com/LAAC-LSCP/ChildRecordsData/files/5829035/LENAExport_ITSFiles_202012350_091222.zip)

**Comment by lucasgautheron** [comment]
The current code (2558028fc5952c54a190a952d1a052080438eac9) supports both formats, except it ignores some of the information contained in the latter, more specifically the details of children utterances.

**Comment by alecristia** [comment]
lena_speaker_translation_table = {
    'CHN': 'CHI',
    'CXN': 'OCH',
    'FAN': 'FEM',
    'MAN': 'MAL'
}
